#!/usr/bin/env node
import assert from "node:assert/strict";
import admin from "firebase-admin";
import { buildRandomSingleEliminationBracket, applySingleEliminationWinner, getSingleEliminationBracketSize } from "../assets/js/competition/singleElimination.js";
import { TECH1DRIFT_ANNIVERSARY_CONFIG, buildTech1AnniversaryShell } from "../assets/js/config/specialEvents.js";
import {
  buildTech1PublicRegistrationIndexDoc,
  buildTech1RaffleTransactionDoc,
  buildTech1RegistrationDoc,
  mergeTech1RegistrationTicketPurchase,
} from "../assets/js/data/tech1AnniversaryAdapter.js";

function parseArgs(argv) {
  const parsed = { _: [] };
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith("--")) {
      parsed._.push(token);
      continue;
    }
    const key = token.slice(2);
    const next = argv[index + 1];
    if (!next || next.startsWith("--")) {
      parsed[key] = true;
    } else {
      parsed[key] = next;
      index += 1;
    }
  }
  return parsed;
}

function usage() {
  return `
Usage:
  npm run tech1:dry-run -- 5
  npm run tech1:dry-run -- 60
  node scripts/tech1-dry-run.mjs --project <stagingProject> --app-id <stagingAppId> --event tech1drift-anniversary-may-30 --driver-count 5 --write --yes

Defaults:
  - dry-run only, no Firebase writes
  - all fake drivers checked in
  - sample paid raffle tickets included
  - bracket generated from checked-in drivers

Safety:
  Writes require --write --yes, --project, --app-id, and the exact Tech 1 event id.
  Production-looking projects are refused unless --allow-production is provided.
  Fake docs use obvious dry-run ids and names.
`.trim();
}

function assertSafeTarget(args) {
  const eventId = String(args.event || process.env.npm_config_event || TECH1DRIFT_ANNIVERSARY_CONFIG.eventId).trim();
  if (eventId !== TECH1DRIFT_ANNIVERSARY_CONFIG.eventId) {
    throw new Error(`Wrong --event. Expected ${TECH1DRIFT_ANNIVERSARY_CONFIG.eventId}.`);
  }
  const wantsWrite = Boolean(args.write || process.env.npm_config_write === "true");
  if (!wantsWrite) return { eventId, projectId: "", appId: "" };
  const projectId = String(args.project || process.env.npm_config_project || "").trim();
  const appId = String(args["app-id"] || args.appId || process.env.npm_config_app_id || "").trim();
  if (!projectId) throw new Error("Missing --project for write mode.");
  if (!appId) throw new Error("Missing --app-id for write mode.");
  if (!args.yes && process.env.npm_config_yes !== "true") throw new Error("Write mode requires --yes.");
  const projectLooksProduction = projectId === "prodigy-rc-competitions" || /prod/i.test(projectId);
  if (projectLooksProduction && !args["allow-production"] && process.env.npm_config_allow_production !== "true") {
    throw new Error("Refusing to write Tech 1 dry-run data to a production-looking project without --allow-production.");
  }
  return { eventId, projectId, appId };
}

function seededRandom(seed = 1) {
  let state = Math.max(1, Number(seed || 1));
  return () => {
    state = (state * 48271) % 0x7fffffff;
    return state / 0x7fffffff;
  };
}

function buildFakeRegistrationInput(index, dryRunId, checkedIn) {
  const number = String(index + 1).padStart(3, "0");
  return {
    id: `${dryRunId}-driver-${number}`,
    name: `TECH1 DRY RUN Driver ${number}`,
    teamName: `Dry Run Team ${((index % 6) + 1)}`,
    chassis: index % 2 === 0 ? "Yokomo RD2.0" : "MST RMX",
    instagram: `@tech1_dryrun_${number}`,
    checkedIn,
    bracketEligible: checkedIn,
    staffNotes: "Generated by tech1-dry-run.mjs",
  };
}

function buildDryRunData({ driverCount, checkedIn = true, paidSamples = true, generateBracket = true, dryRunId }) {
  const nowIso = "2026-05-30T12:00:00.000Z";
  const registrations = [];
  const publicIndex = [];
  const raffleTransactions = [];

  for (let index = 0; index < driverCount; index += 1) {
    const registration = buildTech1RegistrationDoc(buildFakeRegistrationInput(index, dryRunId, checkedIn), {
      eventId: TECH1DRIFT_ANNIVERSARY_CONFIG.eventId,
      registrationId: `${dryRunId}-driver-${String(index + 1).padStart(3, "0")}`,
      ownerUid: `${dryRunId}-fake-owner-${String(index + 1).padStart(3, "0")}`,
      nowIso,
    });
    registrations.push(registration);
  }

  if (paidSamples) {
    registrations.forEach((registration, index) => {
      if (index % 4 !== 0) return;
      const paidTicketsAdded = (index % 3) + 1;
      const transaction = buildTech1RaffleTransactionDoc({
        id: `${dryRunId}-raffle-${String(index + 1).padStart(3, "0")}`,
        registrationId: registration.id,
        paidTicketsAdded,
        paymentMethod: index % 8 === 0 ? "cash" : "card",
      }, {
        eventId: TECH1DRIFT_ANNIVERSARY_CONFIG.eventId,
        transactionId: `${dryRunId}-raffle-${String(index + 1).padStart(3, "0")}`,
        confirmedBy: `${dryRunId}-event-staff`,
        nowIso,
      });
      raffleTransactions.push(transaction);
      registrations[index] = mergeTech1RegistrationTicketPurchase(registration, transaction, { nowIso });
    });
  }

  registrations.forEach((registration) => {
    publicIndex.push(buildTech1PublicRegistrationIndexDoc(registration, { nowIso }));
  });

  const eligibleCount = registrations.filter((entry) => checkedIn ? entry.checkedIn : true).length;
  const bracket = generateBracket && eligibleCount >= 2
    ? buildRandomSingleEliminationBracket(registrations, {
        source: TECH1DRIFT_ANNIVERSARY_CONFIG.defaultBracketSource,
        random: seededRandom(driverCount),
        nowIso,
        createdBy: `${dryRunId}-event-staff`,
      })
    : null;

  return { registrations, publicIndex, raffleTransactions, bracket };
}

function advanceBracketToWinner(bracket) {
  let current = JSON.parse(JSON.stringify(bracket || {}));
  let guard = 0;
  while (current?.status !== "complete" && guard < 500) {
    const playable = Object.values(current.matches || {}).find((match) => match.driverA && match.driverB && !match.winnerId);
    if (!playable) break;
    current = applySingleEliminationWinner(current, playable.id, playable.driverA.id, {
      nowIso: "2026-05-30T13:00:00.000Z",
    });
    guard += 1;
  }
  return current;
}

function summarizeDryRun(data) {
  const registrations = data.registrations || [];
  const bracket = data.bracket || null;
  const paidTickets = registrations.reduce((sum, entry) => sum + Number(entry.paidTickets || 0), 0);
  const freeTickets = registrations.reduce((sum, entry) => sum + Number(entry.freeTickets || 0), 0);
  const totalTickets = registrations.reduce((sum, entry) => sum + Number(entry.totalTickets || 0), 0);
  const amountCollected = registrations.reduce((sum, entry) => sum + Number(entry.amountPaid || 0), 0);
  return {
    registrations: registrations.length,
    checkedInDrivers: registrations.filter((entry) => entry.checkedIn).length,
    paidTickets,
    freeTickets,
    totalRaffleTickets: totalTickets,
    amountCollected,
    bracketSource: bracket?.source || "",
    bracketSize: bracket?.bracketSize || 0,
    byes: bracket?.byes?.length || 0,
    randomizedSeedOrder: bracket?.randomizedSeedOrder?.length || 0,
  };
}

function assertDryRun(summary, driverCount) {
  assert.equal(summary.registrations, driverCount);
  assert.equal(summary.freeTickets, driverCount);
  assert.equal(summary.checkedInDrivers, driverCount);
  if (driverCount >= 2) {
    assert.equal(summary.bracketSource, TECH1DRIFT_ANNIVERSARY_CONFIG.defaultBracketSource);
    assert.equal(summary.bracketSize, getSingleEliminationBracketSize(driverCount));
    assert.equal(summary.byes, summary.bracketSize - driverCount);
    assert.equal(summary.randomizedSeedOrder, driverCount);
  }
}

async function writeDryRunData({ projectId, appId, eventId, dryRunId, data }) {
  admin.initializeApp({
    credential: admin.credential.applicationDefault(),
    projectId,
  });
  const db = admin.firestore();
  const basePath = `artifacts/${appId}/public/data/specialEvents/${eventId}`;
  const batch = db.batch();
  batch.set(db.doc(basePath), buildTech1AnniversaryShell({
    registrationOpen: true,
    updatedAt: new Date().toISOString(),
    dryRunId,
  }), { merge: true });
  data.registrations.forEach((registration, index) => {
    batch.set(db.doc(`${basePath}/registrations/${registration.id}`), {
      ...registration,
      dryRunId,
    }, { merge: true });
    batch.set(db.doc(`${basePath}/publicRegistrationIndex/${data.publicIndex[index].registrationId}`), {
      ...data.publicIndex[index],
      dryRunId,
    }, { merge: true });
  });
  data.raffleTransactions.forEach((transaction) => {
    batch.set(db.doc(`${basePath}/raffleTransactions/${transaction.id}`), {
      ...transaction,
      dryRunId,
    }, { merge: true });
  });
  if (data.bracket) {
    batch.set(db.doc(`${basePath}/brackets/main`), {
      ...data.bracket,
      dryRunId,
    }, { merge: true });
  }
  await batch.commit();
  return basePath;
}

async function cleanupDryRunData({ projectId, appId, eventId, dryRunId }) {
  admin.initializeApp({
    credential: admin.credential.applicationDefault(),
    projectId,
  });
  const db = admin.firestore();
  const basePath = `artifacts/${appId}/public/data/specialEvents/${eventId}`;
  const collections = ["registrations", "publicRegistrationIndex", "raffleTransactions"];
  let deleted = 0;
  for (const collectionName of collections) {
    const snap = await db.collection(`${basePath}/${collectionName}`).where("dryRunId", "==", dryRunId).get();
    const batch = db.batch();
    snap.docs.forEach((docSnap) => {
      batch.delete(docSnap.ref);
      deleted += 1;
    });
    if (!snap.empty) await batch.commit();
  }
  const bracketRef = db.doc(`${basePath}/brackets/main`);
  const bracketSnap = await bracketRef.get();
  if (bracketSnap.exists && bracketSnap.data()?.dryRunId === dryRunId) {
    await bracketRef.delete();
    deleted += 1;
  }
  return { basePath, deleted };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log(usage());
    return;
  }
  const { eventId, projectId, appId } = assertSafeTarget(args);
  const driverCount = Number.parseInt(args["driver-count"] || args.driverCount || process.env.npm_config_driver_count || args._[0] || "5", 10);
  if (!Number.isInteger(driverCount) || driverCount < 0 || driverCount > 512) {
    throw new Error("Invalid --driver-count. Use an integer from 0 to 512.");
  }
  const dryRunId = String(args["dry-run-id"] || `tech1-dryrun-${driverCount}`).replace(/[^\w-]+/g, "-");

  const wantsWrite = Boolean(args.write || process.env.npm_config_write === "true");
  const wantsCleanup = Boolean(args.cleanup || process.env.npm_config_cleanup === "true");
  const wantsYes = Boolean(args.yes || process.env.npm_config_yes === "true");

  if (wantsCleanup) {
    if (!wantsWrite || !wantsYes) throw new Error("Cleanup requires --write --yes.");
    const result = await cleanupDryRunData({ projectId, appId, eventId, dryRunId });
    console.log(JSON.stringify({ action: "cleanup", dryRunId, ...result }, null, 2));
    return;
  }

  const data = buildDryRunData({
    driverCount,
    checkedIn: !args["no-check-in"] && process.env.npm_config_no_check_in !== "true",
    paidSamples: !args["no-paid-samples"] && process.env.npm_config_no_paid_samples !== "true",
    generateBracket: !args["no-bracket"] && process.env.npm_config_no_bracket !== "true",
    dryRunId,
  });
  const stableData = buildDryRunData({
    driverCount,
    checkedIn: !args["no-check-in"] && process.env.npm_config_no_check_in !== "true",
    paidSamples: !args["no-paid-samples"] && process.env.npm_config_no_paid_samples !== "true",
    generateBracket: !args["no-bracket"] && process.env.npm_config_no_bracket !== "true",
    dryRunId,
  });
  const summary = summarizeDryRun(data);
  assertDryRun(summary, driverCount);
  assert.deepEqual(data.bracket?.randomizedSeedOrder || [], stableData.bracket?.randomizedSeedOrder || [], "stored seeded order should be stable for the same dry-run input");
  const completedBracket = data.bracket ? advanceBracketToWinner(data.bracket) : null;

  const result = {
    mode: wantsWrite ? "write" : "dry-run",
    dryRunId,
    eventId,
    projectId: projectId || null,
    appId: appId || null,
    summary,
    bracketBlockedReason: data.bracket ? null : "fewer than 2 eligible checked-in drivers",
    finalWinner: completedBracket?.status === "complete"
      ? Object.values(completedBracket.matches || {}).find((match) => !match.advancedToMatchId)?.winnerId || null
      : null,
    willWrite: wantsWrite,
  };

  if (wantsWrite) {
    result.path = await writeDryRunData({ projectId, appId, eventId, dryRunId, data });
  }

  console.log(JSON.stringify(result, null, 2));
}

main().catch((error) => {
  console.error(error.message || error);
  process.exitCode = 1;
});
