#!/usr/bin/env node
import assert from "node:assert/strict";
import admin from "firebase-admin";
import { buildRandomSingleEliminationBracket, applySingleEliminationWinner, getSingleEliminationBracketSize } from "../assets/js/competition/singleElimination.js";
import { calculateCompetitionDecisionResolution } from "../assets/js/competition/battles.js";
import { TECH1DRIFT_ANNIVERSARY_CONFIG, buildTech1AnniversaryShell } from "../assets/js/config/specialEvents.js";
import {
  buildTech1PublicRegistrationIndexDoc,
  buildTech1RaffleTransactionDoc,
  buildTech1RegistrationDoc,
  mergeTech1RegistrationTicketPurchase,
} from "../assets/js/data/tech1AnniversaryAdapter.js";

function parseArgs(argv) {
  const parsed = { _: [] };
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith("--")) {
      parsed._.push(token);
      continue;
    }
    const key = token.slice(2);
    const next = argv[index + 1];
    if (!next || next.startsWith("--")) {
      parsed[key] = true;
    } else {
      parsed[key] = next;
      index += 1;
    }
  }
  return parsed;
}

function usage() {
  return `
Usage:
  npm run tech1:dry-run -- 5
  npm run tech1:dry-run -- 50
  npm run tech1:dry-run -- 60
  npm run tech1:dry-run -- 50 -- --simulate-raffle --simulate-bracket --verify-reveal
  node scripts/tech1-dry-run.mjs --project <stagingProject> --app-id <stagingAppId> --event tech1drift-anniversary-may-30 --driver-count 5 --write --yes

Defaults:
  - dry-run only, no Firebase writes
  - all fake drivers checked in
  - sample paid raffle tickets included; the 50-driver event-admin scenario uses 6-15 extra tickets for every driver
  - bracket generated from drivers marked Competing

Safety:
  Writes require --write --yes, --project, --app-id, and the exact Tech 1 event id.
  Production-looking projects are refused unless --allow-production is provided.
  Fake docs use obvious dry-run ids and names.
`.trim();
}

function assertSafeTarget(args) {
  const eventId = String(args.event || process.env.npm_config_event || TECH1DRIFT_ANNIVERSARY_CONFIG.eventId).trim();
  if (eventId !== TECH1DRIFT_ANNIVERSARY_CONFIG.eventId) {
    throw new Error(`Wrong --event. Expected ${TECH1DRIFT_ANNIVERSARY_CONFIG.eventId}.`);
  }
  const wantsWrite = Boolean(args.write || process.env.npm_config_write === "true");
  if (!wantsWrite) return { eventId, projectId: "", appId: "" };
  const projectId = String(args.project || process.env.npm_config_project || "").trim();
  const appId = String(args["app-id"] || args.appId || process.env.npm_config_app_id || "").trim();
  if (!projectId) throw new Error("Missing --project for write mode.");
  if (!appId) throw new Error("Missing --app-id for write mode.");
  if (!args.yes && process.env.npm_config_yes !== "true") throw new Error("Write mode requires --yes.");
  const projectLooksProduction = projectId === "prodigy-rc-competitions" || /prod/i.test(projectId);
  if (projectLooksProduction && !args["allow-production"] && process.env.npm_config_allow_production !== "true") {
    throw new Error("Refusing to write Tech 1 dry-run data to a production-looking project without --allow-production.");
  }
  return { eventId, projectId, appId };
}

function seededRandom(seed = 1) {
  let state = Math.max(1, Number(seed || 1));
  return () => {
    state = (state * 48271) % 0x7fffffff;
    return state / 0x7fffffff;
  };
}

function getEventDayExtraTickets(index) {
  return 6 + (index % 10);
}

function buildFakeRegistrationInput(index, dryRunId, checkedIn, options = {}) {
  const number = String(index + 1).padStart(3, "0");
  const competing = options.competing !== false;
  return {
    id: `${dryRunId}-driver-${number}`,
    name: `TECH1 DRY RUN Driver ${number}`,
    teamName: `Dry Run Team ${((index % 6) + 1)}`,
    chassis: index % 2 === 0 ? "Yokomo RD2.0" : "MST RMX",
    instagram: `@tech1_dryrun_${number}`,
    checkedIn,
    bracketEligible: competing,
    staffNotes: "Generated by tech1-dry-run.mjs",
  };
}

function buildDryRunData({
  driverCount,
  checkedIn = true,
  paidSamples = true,
  eventDayRaffle = false,
  generateBracket = true,
  dryRunId,
  nonCompetingCount = 0,
}) {
  const nowIso = "2026-05-30T12:00:00.000Z";
  const registrations = [];
  const publicIndex = [];
  const raffleTransactions = [];

  for (let index = 0; index < driverCount; index += 1) {
    const competing = index < Math.max(0, driverCount - nonCompetingCount);
    const registration = buildTech1RegistrationDoc(buildFakeRegistrationInput(index, dryRunId, checkedIn, { competing }), {
      eventId: TECH1DRIFT_ANNIVERSARY_CONFIG.eventId,
      registrationId: `${dryRunId}-driver-${String(index + 1).padStart(3, "0")}`,
      ownerUid: `${dryRunId}-fake-owner-${String(index + 1).padStart(3, "0")}`,
      nowIso,
    });
    registrations.push(registration);
  }

  if (paidSamples) {
    registrations.forEach((registration, index) => {
      if (!eventDayRaffle && index % 4 !== 0) return;
      const paidTicketsAdded = eventDayRaffle ? getEventDayExtraTickets(index) : (index % 3) + 1;
      const transaction = buildTech1RaffleTransactionDoc({
        id: `${dryRunId}-raffle-${String(index + 1).padStart(3, "0")}`,
        registrationId: registration.id,
        paidTicketsAdded,
        paymentMethod: index % 8 === 0 ? "cash" : "card",
      }, {
        eventId: TECH1DRIFT_ANNIVERSARY_CONFIG.eventId,
        transactionId: `${dryRunId}-raffle-${String(index + 1).padStart(3, "0")}`,
        confirmedBy: `${dryRunId}-event-staff`,
        nowIso,
      });
      raffleTransactions.push(transaction);
      registrations[index] = mergeTech1RegistrationTicketPurchase(registration, transaction, { nowIso });
    });
  }

  registrations.forEach((registration) => {
    publicIndex.push(buildTech1PublicRegistrationIndexDoc(registration, { nowIso }));
  });

  const eligibleCount = registrations.filter((entry) => (
    TECH1DRIFT_ANNIVERSARY_CONFIG.defaultBracketSource === "bracketEligible"
      ? entry.bracketEligible
      : checkedIn
        ? entry.checkedIn
        : true
  )).length;
  const bracket = generateBracket && eligibleCount >= 2
    ? buildRandomSingleEliminationBracket(registrations, {
        source: TECH1DRIFT_ANNIVERSARY_CONFIG.defaultBracketSource,
        random: seededRandom(driverCount),
        nowIso,
        createdBy: `${dryRunId}-event-staff`,
      })
    : null;

  return { registrations, publicIndex, raffleTransactions, bracket };
}

function advanceBracketToWinner(bracket) {
  let current = JSON.parse(JSON.stringify(bracket || {}));
  let guard = 0;
  while (current?.status !== "complete" && guard < 500) {
    const playable = Object.values(current.matches || {}).find((match) => match.driverA && match.driverB && !match.winnerId);
    if (!playable) break;
    current = applySingleEliminationWinner(current, playable.id, playable.driverA.id, {
      nowIso: "2026-05-30T13:00:00.000Z",
    });
    guard += 1;
  }
  return current;
}

function simulateSoloDriverJudgeFlowForTech1(bracket) {
  const current = JSON.parse(JSON.stringify(bracket || {}));
  const playable = Object.values(current.matches || {}).find((match) => match.driverA && match.driverB && !match.winnerId);
  if (!playable) return null;
  const control = {
    status: "voting",
    cycle: 1,
    matchId: playable.id,
    entry: {
      bracketKey: "tech1",
      matchId: playable.id,
      title: playable.roundName || `Round ${playable.round}`,
      meta: `Match ${playable.matchNumber}`,
      match: {
        left: playable.driverA,
        right: playable.driverB,
      },
    },
    votes: {
      j1: "left",
      j2: "left",
      j3: "right",
    },
  };
  const resolution = calculateCompetitionDecisionResolution(control, {
    activeRoles: ["j1", "j2", "j3"],
    teamTandemMode: false,
  });
  assert.equal(resolution.allVoted, true, "Tech 1 inherited judge flow should wait for all 3 judges");
  assert.equal(resolution.winnerSide, "left", "Tech 1 inherited judge flow should resolve by solo-driver majority vote");
  const winnerId = playable.driverA.id;
  const advancedBracket = applySingleEliminationWinner(current, playable.id, winnerId, {
    nowIso: "2026-05-30T12:30:00.000Z",
  });
  assert.equal(advancedBracket.matches[playable.id].winnerId, winnerId, "Tech 1 judge decision should advance the selected winner");
  assert.deepEqual(advancedBracket.randomizedSeedOrder, current.randomizedSeedOrder, "judge decisions must not reshuffle Tech 1 seed order");
  return {
    matchId: playable.id,
    votesSubmitted: resolution.submittedCount,
    activeJudges: resolution.activeRoles.length,
    winnerSide: resolution.winnerSide,
    winnerId,
    bracketStatusAfterVote: advancedBracket.status,
  };
}

function summarizeDryRun(data) {
  const registrations = data.registrations || [];
  const bracket = data.bracket || null;
  const paidTickets = registrations.reduce((sum, entry) => sum + Number(entry.paidTickets || 0), 0);
  const freeTickets = registrations.reduce((sum, entry) => sum + Number(entry.freeTickets || 0), 0);
  const totalTickets = registrations.reduce((sum, entry) => sum + Number(entry.totalTickets || 0), 0);
  const entryFeesCollected = registrations.reduce((sum) => (
    sum + Number(TECH1DRIFT_ANNIVERSARY_CONFIG.entryFee || 0)
  ), 0);
  const raffleAmountCollected = registrations.reduce((sum, entry) => sum + Number(entry.amountPaid || 0), 0);
  const amountCollected = registrations.reduce((sum, entry) => (
    sum + Number(TECH1DRIFT_ANNIVERSARY_CONFIG.entryFee || 0) + Number(entry.amountPaid || 0)
  ), 0);
  return {
    registrations: registrations.length,
    checkedInDrivers: registrations.filter((entry) => entry.checkedIn).length,
    competingDrivers: registrations.filter((entry) => entry.bracketEligible).length,
    nonCompetingDrivers: registrations.filter((entry) => !entry.bracketEligible).length,
    paidTickets,
    freeTickets,
    totalRaffleTickets: totalTickets,
    entryFeesCollected,
    raffleAmountCollected,
    amountCollected,
    allDriversHaveMoreThanFiveExtraTickets: registrations.every((entry) => Number(entry.paidTickets || 0) > 5),
    bracketSource: bracket?.source || "",
    bracketSize: bracket?.bracketSize || 0,
    byes: bracket?.byes?.length || 0,
    randomizedSeedOrder: bracket?.randomizedSeedOrder?.length || 0,
  };
}

function assertDryRun(summary, driverCount) {
  assert.equal(summary.registrations, driverCount);
  assert.equal(summary.freeTickets, driverCount);
  assert.equal(summary.checkedInDrivers, driverCount);
  if (driverCount >= 2) {
    assert.equal(summary.bracketSource, TECH1DRIFT_ANNIVERSARY_CONFIG.defaultBracketSource);
    assert.equal(summary.bracketSize, getSingleEliminationBracketSize(summary.competingDrivers));
    assert.equal(summary.byes, summary.bracketSize - summary.competingDrivers);
    assert.equal(summary.randomizedSeedOrder, summary.competingDrivers);
  }
}

function summarizeRevealFlow(bracket) {
  if (!bracket) {
    return {
      beforeGenerated: "hidden",
      generatedBeforeBattles: "hidden",
      finalCompleteBeforeClick: "not_available",
      afterClickReveal: "not_available",
    };
  }
  const completedBracket = advanceBracketToWinner(bracket);
  assert.equal(completedBracket.status, "complete", "dry-run bracket should advance to one winner");
  assert.equal(completedBracket.winnerRevealStatus || "hidden", "hidden", "final winner remains hidden before click reveal");
  assert.equal(completedBracket.winnerRevealedAt || null, null, "final winner reveal timestamp should not be set before click reveal");
  const revealedBracket = {
    ...completedBracket,
    winnerRevealStatus: "revealed",
    winnerRevealedAt: "2026-05-30T13:30:00.000Z",
    winnerRevealUpdatedBy: "tech1-dryrun-event-staff",
  };
  return {
    beforeGenerated: "hidden",
    generatedBeforeBattles: "hidden",
    finalCompleteBeforeClick: completedBracket.winnerRevealStatus || "hidden",
    afterClickReveal: revealedBracket.winnerRevealStatus,
    revealPersistsAfterReload: Boolean(revealedBracket.winnerRevealedAt),
  };
}

async function writeDryRunData({ projectId, appId, eventId, dryRunId, data }) {
  admin.initializeApp({
    credential: admin.credential.applicationDefault(),
    projectId,
  });
  const db = admin.firestore();
  const basePath = `artifacts/${appId}/public/data/specialEvents/${eventId}`;
  const batch = db.batch();
  batch.set(db.doc(basePath), buildTech1AnniversaryShell({
    registrationOpen: true,
    updatedAt: new Date().toISOString(),
    dryRunId,
  }), { merge: true });
  data.registrations.forEach((registration, index) => {
    batch.set(db.doc(`${basePath}/registrations/${registration.id}`), {
      ...registration,
      dryRunId,
    }, { merge: true });
    batch.set(db.doc(`${basePath}/publicRegistrationIndex/${data.publicIndex[index].registrationId}`), {
      ...data.publicIndex[index],
      dryRunId,
    }, { merge: true });
  });
  data.raffleTransactions.forEach((transaction) => {
    batch.set(db.doc(`${basePath}/raffleTransactions/${transaction.id}`), {
      ...transaction,
      dryRunId,
    }, { merge: true });
  });
  if (data.bracket) {
    batch.set(db.doc(`${basePath}/brackets/main`), {
      ...data.bracket,
      dryRunId,
    }, { merge: true });
  }
  await batch.commit();
  return basePath;
}

async function cleanupDryRunData({ projectId, appId, eventId, dryRunId }) {
  admin.initializeApp({
    credential: admin.credential.applicationDefault(),
    projectId,
  });
  const db = admin.firestore();
  const basePath = `artifacts/${appId}/public/data/specialEvents/${eventId}`;
  const collections = ["registrations", "publicRegistrationIndex", "raffleTransactions"];
  let deleted = 0;
  for (const collectionName of collections) {
    const snap = await db.collection(`${basePath}/${collectionName}`).where("dryRunId", "==", dryRunId).get();
    const batch = db.batch();
    snap.docs.forEach((docSnap) => {
      batch.delete(docSnap.ref);
      deleted += 1;
    });
    if (!snap.empty) await batch.commit();
  }
  const bracketRef = db.doc(`${basePath}/brackets/main`);
  const bracketSnap = await bracketRef.get();
  if (bracketSnap.exists && bracketSnap.data()?.dryRunId === dryRunId) {
    await bracketRef.delete();
    deleted += 1;
  }
  return { basePath, deleted };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log(usage());
    return;
  }
  const { eventId, projectId, appId } = assertSafeTarget(args);
  const driverCount = Number.parseInt(args["driver-count"] || args.driverCount || process.env.npm_config_driver_count || args._[0] || "5", 10);
  if (!Number.isInteger(driverCount) || driverCount < 0 || driverCount > 512) {
    throw new Error("Invalid --driver-count. Use an integer from 0 to 512.");
  }
  const dryRunId = String(args["dry-run-id"] || `tech1-dryrun-${driverCount}`).replace(/[^\w-]+/g, "-");

  const wantsWrite = Boolean(args.write || process.env.npm_config_write === "true");
  const wantsCleanup = Boolean(args.cleanup || process.env.npm_config_cleanup === "true");
  const wantsYes = Boolean(args.yes || process.env.npm_config_yes === "true");
  const simulateRaffle = Boolean(args["simulate-raffle"] || process.env.npm_config_simulate_raffle === "true" || driverCount === 50);
  const simulateBracket = args["simulate-bracket"] !== false && process.env.npm_config_simulate_bracket !== "false";
  const verifyReveal = Boolean(args["verify-reveal"] || process.env.npm_config_verify_reveal === "true" || driverCount === 50);

  if (wantsCleanup) {
    if (!wantsWrite || !wantsYes) throw new Error("Cleanup requires --write --yes.");
    const result = await cleanupDryRunData({ projectId, appId, eventId, dryRunId });
    console.log(JSON.stringify({ action: "cleanup", dryRunId, ...result }, null, 2));
    return;
  }

  const data = buildDryRunData({
    driverCount,
    checkedIn: !args["no-check-in"] && process.env.npm_config_no_check_in !== "true",
    paidSamples: !args["no-paid-samples"] && process.env.npm_config_no_paid_samples !== "true",
    eventDayRaffle: simulateRaffle,
    generateBracket: simulateBracket && !args["no-bracket"] && process.env.npm_config_no_bracket !== "true",
    dryRunId,
  });
  const stableData = buildDryRunData({
    driverCount,
    checkedIn: !args["no-check-in"] && process.env.npm_config_no_check_in !== "true",
    paidSamples: !args["no-paid-samples"] && process.env.npm_config_no_paid_samples !== "true",
    eventDayRaffle: simulateRaffle,
    generateBracket: simulateBracket && !args["no-bracket"] && process.env.npm_config_no_bracket !== "true",
    dryRunId,
  });
  const summary = summarizeDryRun(data);
  assertDryRun(summary, driverCount);
  assert.deepEqual(data.bracket?.randomizedSeedOrder || [], stableData.bracket?.randomizedSeedOrder || [], "stored seeded order should be stable for the same dry-run input");
  const completedBracket = data.bracket ? advanceBracketToWinner(data.bracket) : null;
  const judgeFlow = data.bracket ? simulateSoloDriverJudgeFlowForTech1(data.bracket) : null;
  if (driverCount === 50) {
    assert.equal(summary.paidTickets, 525, "50-driver event-day pattern should total 525 extra tickets");
    assert.equal(summary.totalRaffleTickets, 575, "50-driver event-day pattern should total 575 raffle tickets");
    assert.equal(summary.entryFeesCollected, 2000, "50 registered drivers should collect $2000 in entry fees");
    assert.equal(summary.raffleAmountCollected, 2625, "50-driver event-day pattern should collect $2625 in raffle tickets at $5 each");
    assert.equal(summary.amountCollected, 4625, "50-driver event-day pattern should collect $4625 total");
    assert.equal(summary.allDriversHaveMoreThanFiveExtraTickets, true, "every simulated driver should buy more than 5 extra tickets");
    assert.equal(summary.bracketSize, 64);
    assert.equal(summary.byes, 14);
  }

  const nonCompetingVariant = driverCount === 50
    ? summarizeDryRun(buildDryRunData({
        driverCount: 55,
        checkedIn: !args["no-check-in"] && process.env.npm_config_no_check_in !== "true",
        paidSamples: !args["no-paid-samples"] && process.env.npm_config_no_paid_samples !== "true",
        eventDayRaffle: true,
        generateBracket: true,
        dryRunId: `${dryRunId}-noncompeting-variant`,
        nonCompetingCount: 5,
      }))
    : null;
  if (nonCompetingVariant) {
    assert.equal(nonCompetingVariant.registrations, 55);
    assert.equal(nonCompetingVariant.competingDrivers, 50);
    assert.equal(nonCompetingVariant.nonCompetingDrivers, 5);
    assert.equal(nonCompetingVariant.entryFeesCollected, 2200);
    assert.equal(nonCompetingVariant.bracketSize, 64);
    assert.equal(nonCompetingVariant.byes, 14);
    assert.equal(nonCompetingVariant.randomizedSeedOrder, 50);
  }

  const result = {
    mode: wantsWrite ? "write" : "dry-run",
    dryRunId,
    eventId,
    projectId: projectId || null,
    appId: appId || null,
    summary,
    bracketBlockedReason: data.bracket ? null : "fewer than 2 eligible competing drivers",
    finalWinner: completedBracket?.status === "complete"
      ? Object.values(completedBracket.matches || {}).find((match) => !match.advancedToMatchId)?.winnerId || null
      : null,
    revealFlow: verifyReveal ? summarizeRevealFlow(data.bracket) : null,
    judgeFlow,
    rafflePattern: simulateRaffle
      ? "event-admin 6-15 extra tickets per driver"
      : "sample every fourth driver",
    nonCompetingVariant,
    willWrite: wantsWrite,
  };

  if (wantsWrite) {
    result.path = await writeDryRunData({ projectId, appId, eventId, dryRunId, data });
  }

  console.log(JSON.stringify(result, null, 2));
}

main().catch((error) => {
  console.error(error.message || error);
  process.exitCode = 1;
});
